// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUPwg73adznFrxuqTXj_QA8ckXAMVd-E8',
    appId: '1:629013756806:web:94ae596f17918e01720a07',
    messagingSenderId: '629013756806',
    projectId: 'todo-hero-afa21',
    authDomain: 'todo-hero-afa21.firebaseapp.com',
    storageBucket: 'todo-hero-afa21.appspot.com',
    measurementId: 'G-4BGYE9RFQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEKN_hLugBIL-iiWLs-sWHhyellYeAP5c',
    appId: '1:629013756806:android:2eb7703aede4a18b720a07',
    messagingSenderId: '629013756806',
    projectId: 'todo-hero-afa21',
    storageBucket: 'todo-hero-afa21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwU1gLN9FFmGrKhjBNzngfPWPMpRf5sU8',
    appId: '1:629013756806:ios:adb588bb56917298720a07',
    messagingSenderId: '629013756806',
    projectId: 'todo-hero-afa21',
    storageBucket: 'todo-hero-afa21.appspot.com',
    iosClientId: '629013756806-d6m4bsq6urkblvgnq42vabebmbm53gnu.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoHero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwU1gLN9FFmGrKhjBNzngfPWPMpRf5sU8',
    appId: '1:629013756806:ios:adb588bb56917298720a07',
    messagingSenderId: '629013756806',
    projectId: 'todo-hero-afa21',
    storageBucket: 'todo-hero-afa21.appspot.com',
    iosClientId: '629013756806-d6m4bsq6urkblvgnq42vabebmbm53gnu.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoHero',
  );
}
